name: anihelp
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  lottie: ^0.7.0+1
  flutter_signin_button: ^1.1.0
  modal_progress_hud: ^0.1.3
  google_sign_in: ^4.5.9
  google_nav_bar: ^3.2.0
  cached_network_image: ^2.5.0
  mailer: ^3.2.1
  flutter_dotenv: ^3.1.0
  image_picker: ^0.6.7+22
  firebase_storage: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: CarterOne
      fonts:
        - asset: fonts/CarterOne-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf

  assets:
    - assets/
    - .env